# Generated by Django 6.0.1 on 2026-01-27 18:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['pickup_latitude', 'pickup_longitude'], name='ride_pickup_coords'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['dropoff_latitude', 'dropoff_longitude'], name='ride_dropoff_coords'),
        ),
    ]
