# Generated by Django 6.0.1 on 2026-01-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_ride_ride_pickup_coords_ride_ride_dropoff_coords'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ride_event',
            index=models.Index(fields=['id_ride', 'description'], name='ride_id_ride_description'),
        ),
    ]
